// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ParkerGratis_Forms {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ParkerGratis_Forms.Languages.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string FreeWeekend {
            get {
                return ResourceManager.GetString("FreeWeekend", resourceCulture);
            }
        }
        
        internal static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string ParkingDetailsGetDirectionButton {
            get {
                return ResourceManager.GetString("ParkingDetailsGetDirectionButton", resourceCulture);
            }
        }
        
        internal static string ParkingDetailsAbout {
            get {
                return ResourceManager.GetString("ParkingDetailsAbout", resourceCulture);
            }
        }
        
        internal static string ParkingTypeLabel {
            get {
                return ResourceManager.GetString("ParkingTypeLabel", resourceCulture);
            }
        }
        
        internal static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        internal static string ErrorTitleText {
            get {
                return ResourceManager.GetString("ErrorTitleText", resourceCulture);
            }
        }
        
        internal static string Hours5 {
            get {
                return ResourceManager.GetString("Hours5", resourceCulture);
            }
        }
        
        internal static string Hours4 {
            get {
                return ResourceManager.GetString("Hours4", resourceCulture);
            }
        }
        
        internal static string Hours3 {
            get {
                return ResourceManager.GetString("Hours3", resourceCulture);
            }
        }
        
        internal static string Hours2 {
            get {
                return ResourceManager.GetString("Hours2", resourceCulture);
            }
        }
        
        internal static string LatTextLabel {
            get {
                return ResourceManager.GetString("LatTextLabel", resourceCulture);
            }
        }
        
        internal static string ParkingDetailsReportLocationButton {
            get {
                return ResourceManager.GetString("ParkingDetailsReportLocationButton", resourceCulture);
            }
        }
        
        internal static string NameLabelText {
            get {
                return ResourceManager.GetString("NameLabelText", resourceCulture);
            }
        }
        
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        internal static string SuccessReportingMessage {
            get {
                return ResourceManager.GetString("SuccessReportingMessage", resourceCulture);
            }
        }
        
        internal static string AdditionalInfoLabelText {
            get {
                return ResourceManager.GetString("AdditionalInfoLabelText", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string NoNameWhenAddingParkingError {
            get {
                return ResourceManager.GetString("NoNameWhenAddingParkingError", resourceCulture);
            }
        }
        
        internal static string FreeCommute {
            get {
                return ResourceManager.GetString("FreeCommute", resourceCulture);
            }
        }
        
        internal static string ParkingDetailsAddress {
            get {
                return ResourceManager.GetString("ParkingDetailsAddress", resourceCulture);
            }
        }
        
        internal static string AddLocationButtonText {
            get {
                return ResourceManager.GetString("AddLocationButtonText", resourceCulture);
            }
        }
        
        internal static string LongTextLabel {
            get {
                return ResourceManager.GetString("LongTextLabel", resourceCulture);
            }
        }
        
        internal static string OtherLabelText {
            get {
                return ResourceManager.GetString("OtherLabelText", resourceCulture);
            }
        }
        
        internal static string ParkingTypesLabel {
            get {
                return ResourceManager.GetString("ParkingTypesLabel", resourceCulture);
            }
        }
        
        internal static string ParkingDetailsDistance {
            get {
                return ResourceManager.GetString("ParkingDetailsDistance", resourceCulture);
            }
        }
        
        internal static string ParkingDetailsType {
            get {
                return ResourceManager.GetString("ParkingDetailsType", resourceCulture);
            }
        }
        
        internal static string CenterPinText {
            get {
                return ResourceManager.GetString("CenterPinText", resourceCulture);
            }
        }
        
        internal static string MapPageTitle {
            get {
                return ResourceManager.GetString("MapPageTitle", resourceCulture);
            }
        }
        
        internal static string SearchBarPlaceHolderText {
            get {
                return ResourceManager.GetString("SearchBarPlaceHolderText", resourceCulture);
            }
        }
        
        internal static string FreeGivenTime {
            get {
                return ResourceManager.GetString("FreeGivenTime", resourceCulture);
            }
        }
        
        internal static string ParkingDetailsOtherInfo {
            get {
                return ResourceManager.GetString("ParkingDetailsOtherInfo", resourceCulture);
            }
        }
        
        internal static string ParkingDetailsAddInfo {
            get {
                return ResourceManager.GetString("ParkingDetailsAddInfo", resourceCulture);
            }
        }
        
        internal static string ParkingDetailsVerifyLocationButton {
            get {
                return ResourceManager.GetString("ParkingDetailsVerifyLocationButton", resourceCulture);
            }
        }
        
        internal static string SuccessAddedParkingMessage {
            get {
                return ResourceManager.GetString("SuccessAddedParkingMessage", resourceCulture);
            }
        }
        
        internal static string ParkingDetailsReportedTitle {
            get {
                return ResourceManager.GetString("ParkingDetailsReportedTitle", resourceCulture);
            }
        }
        
        internal static string NewParkingPageTitle {
            get {
                return ResourceManager.GetString("NewParkingPageTitle", resourceCulture);
            }
        }
        
        internal static string SuccessVerifyingMessage {
            get {
                return ResourceManager.GetString("SuccessVerifyingMessage", resourceCulture);
            }
        }
        
        internal static string GeneralErrorMessage {
            get {
                return ResourceManager.GetString("GeneralErrorMessage", resourceCulture);
            }
        }
        
        internal static string AddressTextLabel {
            get {
                return ResourceManager.GetString("AddressTextLabel", resourceCulture);
            }
        }
        
        internal static string FreeWithTicket {
            get {
                return ResourceManager.GetString("FreeWithTicket", resourceCulture);
            }
        }
        
        internal static string FreeStreetPark {
            get {
                return ResourceManager.GetString("FreeStreetPark", resourceCulture);
            }
        }
        
        internal static string ParkingDetailsVerifiedTitle {
            get {
                return ResourceManager.GetString("ParkingDetailsVerifiedTitle", resourceCulture);
            }
        }
        
        internal static string OtherTypeSelectedButNoDescText {
            get {
                return ResourceManager.GetString("OtherTypeSelectedButNoDescText", resourceCulture);
            }
        }
    }
}
